apiVersion: v1
kind: Service
metadata:
  name: csc-ui-service
  labels:
    app: csc-ui-app
spec:
  ports:
    - name: csc-ui-app
      port: 80
      targetPort: 80
  selector:
    app: csc-ui-app
  type: ClusterIP
